### ISSUE TITLE
not able to install under python3

### ISSUE THREAD

**Issue by tonino0013** [mbagagli/filterpicker#1]
Dear @mbagagli,
I work on Ubuntu 16.04 LTS with python3.5.2, obspy 1.1.0
I tried to install the through pypi but the repository is not present. Downloading from  here and following the procedure did not work, I have the following error:
`ERROR: Package 'filterpicker' requires a different Python: 3.5.2 not in '>=3.6'`

The package is for python3.6 or up?,
regards

**Comment by mbagagli** [comment]
Dear @tonino0013 
now the support for Python 3.5 is added. I didn't upload the new version (1.0.5) to PyPI yet. 
You will need to clone the master for the time being. I will create a new PyPI release as soon as I have more features / bug fix ready.

Best
